# Generated by Django 3.2.12 on 2022-05-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTexi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datatimes', models.DateTimeField(verbose_name='时间')),
                ('fkwhere', models.CharField(max_length=20)),
                ('fkemail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('fkmotif', models.TextField(verbose_name='标题')),
                ('fkdetails', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='index.formtexi')),
                ('restore', models.TextField(verbose_name='客服回复')),
            ],
        ),
        migrations.AddField(
            model_name='formtexi',
            name='fkauthor',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='index.userprofile', to_field='username'),
        ),
    ]
