# Generated by Django 3.2.12 on 2022-04-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datatime', models.DateTimeField(verbose_name='时间')),
                ('motif', models.TextField(verbose_name='标题')),
                ('details', models.TextField(verbose_name='内容')),
                ('restore', models.TextField(verbose_name='客服')),
                ('fkauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.userprofile', to_field='username')),
            ],
            options={
                'unique_together': {('fkauthor', 'id')},
            },
        ),
    ]
