# Generated by Django 3.2.12 on 2022-04-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='motif',
            field=models.TextField(verbose_name='标题'),
        ),
    ]
