# Generated by Django 3.2.12 on 2022-04-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTexi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fkauthor', models.CharField(max_length=20, unique=True)),
                ('fkwhere', models.CharField(max_length=20, unique=True)),
                ('fkemail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('fkmotif', models.TextField(verbose_name='标题')),
                ('fkdetails', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
